// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOmTyuiO4MzuR6B0YLhKKYJ_vLypmWwq0',
    appId: '1:762560295100:android:3bc2b57ed168196f26a0b9',
    messagingSenderId: '762560295100',
    projectId: 'quipaesapp',
    storageBucket: 'quipaesapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-eNRivF8Ql2k19K8K_ncRPIzVCZ_vYts',
    appId: '1:762560295100:ios:0d33ef65e47f5c4626a0b9',
    messagingSenderId: '762560295100',
    projectId: 'quipaesapp',
    storageBucket: 'quipaesapp.firebasestorage.app',
    iosBundleId: 'com.example.quipaesapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2gTWWAzAN1ZXxDvGf-jOEoFVUtqf4NL4',
    appId: '1:762560295100:web:f2646677fc290a1d26a0b9',
    messagingSenderId: '762560295100',
    projectId: 'quipaesapp',
    authDomain: 'quipaesapp.firebaseapp.com',
    storageBucket: 'quipaesapp.firebasestorage.app',
  );

}